"""Environment variable names and default configuration for commerce Lambdas."""

COMMERCE_TABLE_ENV = "COMMERCE_TABLE"
DEFAULT_COMMERCE_TABLE = "babesclub-commerce"

QUOTE_TTL_ENV = "QUOTE_TTL_MINUTES"
DEFAULT_QUOTE_TTL_MINUTES = 15

SESSION_TTL_ENV = "SESSION_TTL_MINUTES"
DEFAULT_SESSION_TTL_MINUTES = 60 * 24

EVENT_TTL_ENV = "EVENT_TTL_DAYS"
DEFAULT_EVENT_TTL_DAYS = 90

QUOTE_SIGNATURE_SECRET_ENV = "QUOTE_SIGNATURE_SECRET"
QUOTE_SIGNATURE_SECRET_PARAMETER_ENV = "QUOTE_SIGNATURE_SECRET_PARAMETER"
CORS_ALLOW_ORIGIN_ENV = "CORS_ALLOW_ORIGIN"
CHECKOUT_SUCCESS_URL_ENV = "CHECKOUT_SUCCESS_URL"
CHECKOUT_CANCEL_URL_ENV = "CHECKOUT_CANCEL_URL"
CHECKOUT_MODE_ENV = "CHECKOUT_MODE"
CHECKOUT_ALLOW_PROMOTION_CODES_ENV = "CHECKOUT_ALLOW_PROMOTION_CODES"
CHECKOUT_AUTOMATIC_TAX_ENV = "CHECKOUT_AUTOMATIC_TAX"
STRIPE_SECRET_ENV = "STRIPE_SECRET"
STRIPE_SECRET_PARAMETER_ENV = "STRIPE_SECRET_PARAMETER"
STRIPE_WEBHOOK_SECRET_ENV = "STRIPE_WEBHOOK_SECRET"
STRIPE_WEBHOOK_SECRET_PARAMETER_ENV = "STRIPE_WEBHOOK_SECRET_PARAMETER"
STRIPE_WEBHOOK_TOLERANCE_ENV = "STRIPE_WEBHOOK_TOLERANCE"
